### PR TITLE
Update brownFuncs2.sh

### PR DESCRIPTION
**Pull request by Walkman100**
Added some aliases, you can sort them out

[Review on Reviewable](https://reviewable.io/reviews/deavmi/brownie/5)

### CODE REVIEW

**Comment by deavmi** [comment]
@Walkman100 Will merge soon. ;) Thanks btw :smile:

**Comment by deavmi** [comment]
Are you sure about the `rm` one, it might lead to dreadful mistakes.

**Comment by deavmi** [comment]
What about `rmf`?

**Comment by Walkman100** [comment]
Actually I've figured out `rmdir` is actually a linux command, so that alias should be removed

```shell
pi@WalkmanPI:~ $ which rmdir
/bin/rmdir
```

**Comment by Walkman100** [comment]
@Walkman100 testing my integration

**Comment by deavmi** [comment]
WhY?

**Comment by Walkman100** [comment]
@deavmi why what

**Pull request merged**
